"""add repo_id to node unique constraint

Revision ID: 3cf7340c8c2a
Revises: ccf6d37c9aad
Create Date: 2026-07-29 03:48:50.787023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf7340c8c2a'
down_revision: Union[str, None] = 'ccf6d37c9aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('edges_repo_id_fkey', 'edges', type_='foreignkey')
    op.create_foreign_key(None, 'edges', 'repositories', ['repo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('nodes_name_file_path_key', 'nodes', type_='unique')
    op.create_unique_constraint(None, 'nodes', ['name', 'file_path', 'repo_id'])
    op.drop_constraint('nodes_repo_id_fkey', 'nodes', type_='foreignkey')
    op.create_foreign_key(None, 'nodes', 'repositories', ['repo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.create_foreign_key('nodes_repo_id_fkey', 'nodes', 'repositories', ['repo_id'], ['id'])
    op.drop_constraint(None, 'nodes', type_='unique')
    op.create_unique_constraint('nodes_name_file_path_key', 'nodes', ['name', 'file_path'])
    op.drop_constraint(None, 'edges', type_='foreignkey')
    op.create_foreign_key('edges_repo_id_fkey', 'edges', 'repositories', ['repo_id'], ['id'])
    # ### end Alembic commands ###
