"""unique constraint

Revision ID: c90578f4f0ac
Revises: 327f4911408c
Create Date: 2026-07-09 01:58:54.083232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90578f4f0ac'
down_revision: Union[str, None] = '327f4911408c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'edges', ['caller_id', 'callee_id', 'repo_id'])
    op.create_unique_constraint(None, 'repositories', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='unique')
    op.drop_constraint(None, 'edges', type_='unique')
    # ### end Alembic commands ###
