"""add cascade delete to edge foreign keys

Revision ID: ccf6d37c9aad
Revises: c90578f4f0ac
Create Date: 2026-07-09 03:53:04.894344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf6d37c9aad'
down_revision: Union[str, None] = 'c90578f4f0ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('edges_caller_id_fkey', 'edges', type_='foreignkey')
    op.drop_constraint('edges_callee_id_fkey', 'edges', type_='foreignkey')
    op.create_foreign_key(None, 'edges', 'nodes', ['callee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'edges', 'nodes', ['caller_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'edges', type_='foreignkey')
    op.drop_constraint(None, 'edges', type_='foreignkey')
    op.create_foreign_key('edges_callee_id_fkey', 'edges', 'nodes', ['callee_id'], ['id'])
    op.create_foreign_key('edges_caller_id_fkey', 'edges', 'nodes', ['caller_id'], ['id'])
    # ### end Alembic commands ###
